version: '3'

services:
  mongo-container:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-container-data:/data/db
  mongo-express-container:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-container
  # techworld-redo-container:
  #   image: 309333122116.dkr.ecr.ap-southeast-2.amazonaws.com/techworld-redo-img:dev
  #   ports:
  #     - 3000:3000

volumes:
  mongo-container-data:
    driver: local
